### ISSUE TITLE
Remove all hard-coded references to "Lead" and "Follow" roles

### ISSUE THREAD

**Issue by leetucker** [leetucker/django-danceschool#15]
Since roles are supposed to be configurable, these hard codes will not behave as expected for a school that does not define "Lead" and "Follow."  I believe that the hard-coded references exist in the financial summary tables, as well as in one or two of the school stats graphs.

Also, in core apps.py it is ensured that Lead and Follow roles are created by default, but this should be removed once the hard-codes are removed, since the new "setupschool" command-line command takes care of this for schools that want it.

**Comment by NorthIsUp** [comment]
One thing that Ann always tells me is "I'm not a verb!". So while at it maybe "leader" and "follower"?

**Comment by leetucker** [comment]
I can make the defaults in the setupschool script be "Leader" and "Follower".

However, going forward, I want to eliminate anything that depends on specific role names to work.  This is for two reasons: the potential for internationalization, and the potential for usage by other dance types or activities that don't have "Leader" and "Follower" roles.

As it stands, everything about the roles is configurable already.  The only issue is that if you have roles with names other than "Lead" and "Follow," some of the stats graphs won't show role-based stats for your roles.  I've kept this ticket open because this is just one of those low-priority, pain-in-the-ass things that I don't want to forget to getting around to fixing.

**Comment by leetucker** [comment]
Hooray this is finally done.
